include: package:flutter_lints/flutter.yaml

linter:
  rules:
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true
    use_build_context_synchronously: true

analyzer:
  errors:
    cancel_subscriptions: warning
    close_sinks: warning
    unawaited_futures: warning
    use_build_context_synchronously: warning
