"""
Fine-tune PARSeq on Indian license plate crops.

Uses synthetic dataset generated by generate_synthetic_plates.py (50K+ images)
and/or real annotated crops from operator corrections.

Three-phase training:
    Phase 1: Decoder only (10 epochs, LR=1e-4) — adapt output to Indian charset
    Phase 2: Full model (10 epochs, LR=2e-5) — refine encoder features
    Phase 3: Extended with harder augmentation (20 epochs, LR=5e-6) — push accuracy

Setup on Lightning AI:
    1. pip install torch torchvision timm lmdb nltk
    2. Generate data: python scripts/generate_synthetic_plates.py --count 50000
    3. python scripts/finetune_parseq.py
    4. Download parseq_indian.pt → models/parseq/

Output: parseq_indian.pt (deploy to models/parseq/)
"""

import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms as T

# PARSeq charset for Indian plates
CHARSET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"


class LMDBPlateDataset(Dataset):
    """Read plate crops + labels from LMDB."""

    def __init__(self, lmdb_dir: str, transform=None, max_label_len: int = 12):
        import lmdb as lmdb_lib
        self.env = lmdb_lib.open(lmdb_dir, readonly=True, lock=False)
        with self.env.begin() as txn:
            self.n_samples = int(txn.get(b"num-samples").decode())
        self.transform = transform
        self.max_label_len = max_label_len

    def __len__(self):
        return self.n_samples

    def __getitem__(self, idx):
        import io
        from PIL import Image

        with self.env.begin() as txn:
            img_key = f"image-{idx+1:09d}".encode()
            label_key = f"label-{idx+1:09d}".encode()
            img_bytes = txn.get(img_key)
            label = txn.get(label_key).decode()

        img = Image.open(io.BytesIO(img_bytes)).convert("RGB")
        if self.transform:
            img = self.transform(img)

        # Truncate label
        label = label[:self.max_label_len]
        return img, label

    def __del__(self):
        if hasattr(self, 'env'):
            self.env.close()


class SimpleCollate:
    """Collate with padding for variable-length labels."""
    def __call__(self, batch):
        imgs, labels = zip(*batch)
        imgs = torch.stack(imgs)
        return imgs, list(labels)


def main():
    device = "mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Load pretrained PARSeq
    print("Loading pretrained PARSeq...")
    import ssl
    ssl._create_default_https_context = ssl._create_unverified_context

    local_parseq = Path(__file__).parent.parent / "models" / "parseq"
    if local_parseq.exists() and (local_parseq / "hubconf.py").exists():
        sys.path.insert(0, str(local_parseq))
        model = torch.hub.load(str(local_parseq), "parseq", pretrained=True, source="local", trust_repo=True)
    else:
        model = torch.hub.load("baudm/parseq", "parseq", pretrained=True, trust_repo=True)

    model = model.to(device)
    model.train()

    # Freeze encoder initially, fine-tune decoder
    for name, param in model.named_parameters():
        if "encoder" in name:
            param.requires_grad = False

    # Dataset
    dataset_dir = Path("datasets/indian_plates_lmdb")
    if not (dataset_dir / "train").exists():
        print(f"ERROR: Dataset not found at {dataset_dir}")
        print("Run: python scripts/generate_synthetic_plates.py --count 50000")
        sys.exit(1)

    img_size = model.hparams.img_size  # [32, 128]
    train_transform = T.Compose([
        T.Resize(img_size, T.InterpolationMode.BICUBIC),
        T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
        T.ToTensor(),
        T.Normalize(0.5, 0.5),
    ])
    val_transform = T.Compose([
        T.Resize(img_size, T.InterpolationMode.BICUBIC),
        T.ToTensor(),
        T.Normalize(0.5, 0.5),
    ])

    train_ds = LMDBPlateDataset(str(dataset_dir / "train"), train_transform)
    val_ds = LMDBPlateDataset(str(dataset_dir / "val"), val_transform)

    train_loader = DataLoader(train_ds, batch_size=64, shuffle=True, num_workers=4, collate_fn=SimpleCollate())
    val_loader = DataLoader(val_ds, batch_size=64, shuffle=False, num_workers=4, collate_fn=SimpleCollate())

    print(f"Train: {len(train_ds)}, Val: {len(val_ds)}")

    # Optimizer — lower LR for fine-tuning
    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=1e-4, weight_decay=0.01,
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=20)

    # Training loop
    best_acc = 0.0
    output_path = Path("parseq_indian.pt")

    print("\nFine-tuning PARSeq (decoder only, 10 epochs)...")
    for epoch in range(10):
        model.train()
        total_loss = 0.0
        n_batches = 0

        for imgs, labels in train_loader:
            imgs = imgs.to(device)
            logits, loss, loss_numel = model.forward_logits_loss(imgs, labels)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            total_loss += loss.item()
            n_batches += 1

        scheduler.step()
        avg_loss = total_loss / n_batches if n_batches else 0

        # Validation
        model.eval()
        correct = 0
        total = 0
        with torch.no_grad():
            for imgs, labels in val_loader:
                imgs = imgs.to(device)
                logits = model(imgs)
                probs = logits.softmax(-1)
                preds, _ = model.tokenizer.decode(probs)
                for pred, gt in zip(preds, labels):
                    total += 1
                    if pred.upper().strip() == gt.upper().strip():
                        correct += 1

        acc = correct / total if total else 0
        print(f"  Epoch {epoch+1}/10: loss={avg_loss:.4f}, val_acc={acc:.3f} ({correct}/{total})")

        if acc > best_acc:
            best_acc = acc
            torch.save(model.state_dict(), output_path)

    # Phase 2: unfreeze encoder, lower LR, train 10 more epochs
    print("\nPhase 2: Full fine-tune (encoder + decoder, 10 epochs)...")
    for param in model.parameters():
        param.requires_grad = True

    optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=0.01)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=10)

    for epoch in range(10):
        model.train()
        total_loss = 0.0
        n_batches = 0

        for imgs, labels in train_loader:
            imgs = imgs.to(device)
            logits, loss, loss_numel = model.forward_logits_loss(imgs, labels)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            total_loss += loss.item()
            n_batches += 1

        scheduler.step()
        avg_loss = total_loss / n_batches if n_batches else 0

        model.eval()
        correct = 0
        total = 0
        with torch.no_grad():
            for imgs, labels in val_loader:
                imgs = imgs.to(device)
                logits = model(imgs)
                probs = logits.softmax(-1)
                preds, _ = model.tokenizer.decode(probs)
                for pred, gt in zip(preds, labels):
                    total += 1
                    if pred.upper().strip() == gt.upper().strip():
                        correct += 1

        acc = correct / total if total else 0
        print(f"  Epoch {epoch+1}/10: loss={avg_loss:.4f}, val_acc={acc:.3f} ({correct}/{total})")

        if acc > best_acc:
            best_acc = acc
            torch.save(model.state_dict(), output_path)

    # Phase 3: Extended training with harder augmentation
    print("\nPhase 3: Extended fine-tune (20 epochs, LR=5e-6, harder augmentation)...")

    hard_transform = T.Compose([
        T.Resize(img_size, T.InterpolationMode.BICUBIC),
        T.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.2, hue=0.02),
        T.RandomAffine(degrees=3, translate=(0.05, 0.05), scale=(0.9, 1.1)),
        T.GaussianBlur(kernel_size=3, sigma=(0.1, 1.0)),
        T.ToTensor(),
        T.Normalize(0.5, 0.5),
    ])
    train_ds_hard = LMDBPlateDataset(str(dataset_dir / "train"), hard_transform)
    train_loader_hard = DataLoader(train_ds_hard, batch_size=64, shuffle=True, num_workers=4, collate_fn=SimpleCollate())

    optimizer = torch.optim.AdamW(model.parameters(), lr=5e-6, weight_decay=0.005)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=20)

    for epoch in range(20):
        model.train()
        total_loss = 0.0
        n_batches = 0

        for imgs, labels in train_loader_hard:
            imgs = imgs.to(device)
            logits, loss, loss_numel = model.forward_logits_loss(imgs, labels)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            total_loss += loss.item()
            n_batches += 1

        scheduler.step()
        avg_loss = total_loss / n_batches if n_batches else 0

        model.eval()
        correct = 0
        total = 0
        with torch.no_grad():
            for imgs, labels in val_loader:
                imgs = imgs.to(device)
                logits = model(imgs)
                probs = logits.softmax(-1)
                preds, _ = model.tokenizer.decode(probs)
                for pred, gt in zip(preds, labels):
                    total += 1
                    if pred.upper().strip() == gt.upper().strip():
                        correct += 1

        acc = correct / total if total else 0
        print(f"  Epoch {epoch+1}/20: loss={avg_loss:.4f}, val_acc={acc:.3f} ({correct}/{total})")

        if acc > best_acc:
            best_acc = acc
            torch.save(model.state_dict(), output_path)

    print(f"\nDone! Best accuracy: {best_acc:.3f}")
    print(f"Model saved: {output_path}")
    print(f"\nDeploy: copy {output_path} → models/parseq/parseq_indian.pt")


if __name__ == "__main__":
    main()
