// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCtciv_cLCUGZjyI4mutbQPGHrvyFFfro',
    appId: '1:399747278429:web:9b23a1f2ddf028bec9cfb4',
    messagingSenderId: '399747278429',
    projectId: 'tulanam',
    authDomain: 'tulanam.firebaseapp.com',
    storageBucket: 'tulanam.firebasestorage.app',
    measurementId: 'G-R5R3XF95RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlb5FsA8TDrUXxNEH2jdPBZry_luNsTxg',
    appId: '1:399747278429:android:f65f617a6e94b54dc9cfb4',
    messagingSenderId: '399747278429',
    projectId: 'tulanam',
    storageBucket: 'tulanam.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOCxdXL2neQT-V_kQGoL3gnAYYeOuDMP8',
    appId: '1:399747278429:ios:dc1cb8dcfa7d0e60c9cfb4',
    messagingSenderId: '399747278429',
    projectId: 'tulanam',
    storageBucket: 'tulanam.firebasestorage.app',
    iosBundleId: 'com.yashkawdiya.weighbridge',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOCxdXL2neQT-V_kQGoL3gnAYYeOuDMP8',
    appId: '1:399747278429:ios:33f313766a50167ec9cfb4',
    messagingSenderId: '399747278429',
    projectId: 'tulanam',
    storageBucket: 'tulanam.firebasestorage.app',
    iosBundleId: 'com.example.weighbridgemanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCtciv_cLCUGZjyI4mutbQPGHrvyFFfro',
    appId: '1:399747278429:web:85748f17250b973ac9cfb4',
    messagingSenderId: '399747278429',
    projectId: 'tulanam',
    authDomain: 'tulanam.firebaseapp.com',
    storageBucket: 'tulanam.firebasestorage.app',
    measurementId: 'G-BB3T53TFBN',
  );
  // Linux has no native Firebase app type — it reuses the web config (tulanam).
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDCtciv_cLCUGZjyI4mutbQPGHrvyFFfro',
    appId: '1:399747278429:web:9b23a1f2ddf028bec9cfb4',
    messagingSenderId: '399747278429',
    projectId: 'tulanam',
    authDomain: 'tulanam.firebaseapp.com',
    storageBucket: 'tulanam.firebasestorage.app',
  );
}
