// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXIs-6_oUPoHXl6BOX3SVAWRAtA1xpDds',
    appId: '1:189506147559:web:65fd04d8f472a07d18fe42',
    messagingSenderId: '189506147559',
    projectId: 'weighbridge-management',
    authDomain: 'weighbridge-management.firebaseapp.com',
    storageBucket: 'weighbridge-management.firebasestorage.app',
    measurementId: 'G-9NBYE6DR2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDhPTCTtMQoSdxo5u8NJ1GMdaIjFzI8t4',
    appId: '1:189506147559:android:5c43a6d823085de718fe42',
    messagingSenderId: '189506147559',
    projectId: 'weighbridge-management',
    storageBucket: 'weighbridge-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArqTyP-Tv8yf2_YJ2u0ddpsH5d1hxUGVw',
    appId: '1:189506147559:ios:0ed2e72ea5ebe6ef18fe42',
    messagingSenderId: '189506147559',
    projectId: 'weighbridge-management',
    storageBucket: 'weighbridge-management.firebasestorage.app',
    iosBundleId: 'com.example.weighbridgemanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArqTyP-Tv8yf2_YJ2u0ddpsH5d1hxUGVw',
    appId: '1:189506147559:ios:0ed2e72ea5ebe6ef18fe42',
    messagingSenderId: '189506147559',
    projectId: 'weighbridge-management',
    storageBucket: 'weighbridge-management.firebasestorage.app',
    iosBundleId: 'com.example.weighbridgemanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXIs-6_oUPoHXl6BOX3SVAWRAtA1xpDds',
    appId: '1:189506147559:web:f79dc544bc1d9a7318fe42',
    messagingSenderId: '189506147559',
    projectId: 'weighbridge-management',
    authDomain: 'weighbridge-management.firebaseapp.com',
    storageBucket: 'weighbridge-management.firebasestorage.app',
    measurementId: 'G-Y98QMZ1TC5',
  );
}
